name: Release

on:
  workflow_dispatch:
    inputs:
      dry-run:
        required: true
        type: boolean

concurrency:
  group: ${{ github.workflow }}

jobs:
  ci:
    if: ${{ github.ref_name == 'main' }}
    uses: ./.github/workflows/ci.yml

  release:
    if: ${{ github.ref_name == 'main' }}

    runs-on: ubuntu-latest
    permissions:
      contents: write

    needs: ci

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@d60d37cdb471f034aff80987ec588d58791988ba
      - name: Set Git Authorship Information
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Update Changelog
        run: |
          nix develop -c convco changelog -u $(nix develop -c convco version --bump) > CHANGELOG.md
      - name: Create Release Commit
        run: |
          git add CHANGELOG.md
          git commit -am "release: v$(nix develop -c convco version --bump)"
      - name: Tag Release Commit
        run: |
          version="v$(nix develop -c convco version --bump)"
          git tag -am "$version" "$version"
      - name: Print Dry Run Information
        if: ${{ inputs.dry-run != false || github.ref_name == 'add-release-workflow' }}
        run: |
          git push --dry-run --follow-tags
          git log --graph --oneline
          echo "version: v$(nix develop -c convco version)"
          cat CHANGELOG.md
      - name: Push Release Commit and Tag
        if: ${{ inputs.dry-run == false && github.ref_name != 'add-release-workflow' }}
        run: |
          git push --follow-tags
      - name: Create Release
        if: ${{ inputs.dry-run == false && github.ref_name != 'add-release-workflow' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create \
            "v$(nix develop -c convco version)" \
            --draft \
            --notes "$(nix develop -c convco changelog --max-versions 1)"
